import 'package:datlich/model/chuyen_gia.dart';
import 'package:datlich/model/nghanh_nghe.dart';
import 'package:flutter/material.dart';

const FAKE_NGHANH_NGHE = const [
  NghanhNghe(id: 1, name: "Nhân sự"),
  NghanhNghe(id: 2, name: "Quản lí tài chính"),
  NghanhNghe(id: 3, name: "Pháp lí dân sự"),
  NghanhNghe(id: 4, name: "Bất động sản"),
  NghanhNghe(id: 5, name: "Marketing online"),
  NghanhNghe(id: 6, name: "Sức khỏe cá nhân"),
];
var FAKE_CHUYEN_GIA = [
  ChuyenGia(
      id: 1,
      money: 450000,
      chuyenMon: [1, 3, 6],
      kNLV: "Công ty CPLD ASB_2014-2019, Công ty TNHH ABECO_2020-202x",
      like: 400,
      name: "Hoàng Văn Thành",
      nLBT:
          "Đầu tiên chúng ta nên tìm hiểu đôi chút về khái niệm điểm mạnh. Điểm mạnh (Strengths) là những thế mạnh của bạn về tố chất, kỹ năng, kinh nghiệm hoặc trình độ chuyên môn nổi trội trong đời sống và công việc của bản thân. Mỗi người trong chúng ta đều có các điểm mạnh khác nhau. Nhưng về cơ bản điểm mạnh thường bao gồm:",
      avartar: "assets/avartar/01.jpg"),
  ChuyenGia(
      id: 2,
      money: 290000,
      chuyenMon: [2, 3, 4],
      kNLV: "Công ty CPLD ASB_2014-2019, Công ty TNHH ABECO_2020-202x",
      like: 205,
      name: "Nguyễn Hạnh",
      nLBT: "Đầu tiên chúng ta nên tìm hiểu đôi chút về khái niệm điểm mạnh. Điểm mạnh (Strengths) là những thế mạnh của bạn về tố chất, kỹ năng, kinh nghiệm hoặc trình độ chuyên môn nổi trội trong đời sống và công việc của bản thân. Mỗi người trong chúng ta đều có các điểm mạnh khác nhau. Nhưng về cơ bản điểm mạnh thường bao gồm:",
      avartar: "assets/avartar/02.jpg"),
  ChuyenGia(
      id: 3,
      money: 1150000,
      chuyenMon: [5, 4, 1],
      kNLV: "Công ty CPLD ASB_2014-2019, Công ty TNHH ABECO_2020-202x",
      like: 423,
      name: "Trần Thị Ngân",
      nLBT: "Đầu tiên chúng ta nên tìm hiểu đôi chút về khái niệm điểm mạnh. Điểm mạnh (Strengths) là những thế mạnh của bạn về tố chất, kỹ năng, kinh nghiệm hoặc trình độ chuyên môn nổi trội trong đời sống và công việc của bản thân. Mỗi người trong chúng ta đều có các điểm mạnh khác nhau. Nhưng về cơ bản điểm mạnh thường bao gồm:",
      avartar: "assets/avartar/03.jpg"),
  ChuyenGia(
      id: 4,
      money: 780000,
      chuyenMon: [2, 6],
      kNLV: "Công ty CPLD ASB_2014-2019, Công ty TNHH ABECO_2020-202x",
      like: 535,
      name: "Minh Nguyệt",
      nLBT: "Đầu tiên chúng ta nên tìm hiểu đôi chút về khái niệm điểm mạnh. Điểm mạnh (Strengths) là những thế mạnh của bạn về tố chất, kỹ năng, kinh nghiệm hoặc trình độ chuyên môn nổi trội trong đời sống và công việc của bản thân. Mỗi người trong chúng ta đều có các điểm mạnh khác nhau. Nhưng về cơ bản điểm mạnh thường bao gồm:",
      avartar: "assets/avartar/04.jpg"),
  ChuyenGia(
      id: 5,
      money: 550000,
      chuyenMon: [6],
      kNLV: "Công ty CPLD ASB_2014-2019, Công ty TNHH ABECO_2020-202x",
      like: 135,
      name: "Đào Kiên",
      nLBT: "Đầu tiên chúng ta nên tìm hiểu đôi chút về khái niệm điểm mạnh. Điểm mạnh (Strengths) là những thế mạnh của bạn về tố chất, kỹ năng, kinh nghiệm hoặc trình độ chuyên môn nổi trội trong đời sống và công việc của bản thân. Mỗi người trong chúng ta đều có các điểm mạnh khác nhau. Nhưng về cơ bản điểm mạnh thường bao gồm:",
      avartar: "assets/avartar/05.jpg"),
  ChuyenGia(
      id: 6,
      money: 920000,
      chuyenMon: [1, 6],
      kNLV: "Công ty CPLD ASB_2014-2019, Công ty TNHH ABECO_2020-202x",
      like: 435,
      name: "Lê Hoàng Lan",
      nLBT: "Đầu tiên chúng ta nên tìm hiểu đôi chút về khái niệm điểm mạnh. Điểm mạnh (Strengths) là những thế mạnh của bạn về tố chất, kỹ năng, kinh nghiệm hoặc trình độ chuyên môn nổi trội trong đời sống và công việc của bản thân. Mỗi người trong chúng ta đều có các điểm mạnh khác nhau. Nhưng về cơ bản điểm mạnh thường bao gồm:",
      avartar: "assets/avartar/06.jpg"),
  ChuyenGia(
      id: 7,
      money: 480000,
      chuyenMon: [1, 4],
      kNLV: "Công ty CPLD ASB_2014-2019, Công ty TNHH ABECO_2020-202x",
      like: 635,
      name: "Trần Văn Khởi",
      nLBT: "Đầu tiên chúng ta nên tìm hiểu đôi chút về khái niệm điểm mạnh. Điểm mạnh (Strengths) là những thế mạnh của bạn về tố chất, kỹ năng, kinh nghiệm hoặc trình độ chuyên môn nổi trội trong đời sống và công việc của bản thân. Mỗi người trong chúng ta đều có các điểm mạnh khác nhau. Nhưng về cơ bản điểm mạnh thường bao gồm:",
      avartar: "assets/avartar/07.jpg"),
  ChuyenGia(
      id: 8,
      money: 540000,
      chuyenMon: [4, 2],
      kNLV: "Công ty CPLD ASB_2014-2019, Công ty TNHH ABECO_2020-202x",
      like: 235,
      name: "Nguyễn Hoàng An",
      nLBT: "Đầu tiên chúng ta nên tìm hiểu đôi chút về khái niệm điểm mạnh. Điểm mạnh (Strengths) là những thế mạnh của bạn về tố chất, kỹ năng, kinh nghiệm hoặc trình độ chuyên môn nổi trội trong đời sống và công việc của bản thân. Mỗi người trong chúng ta đều có các điểm mạnh khác nhau. Nhưng về cơ bản điểm mạnh thường bao gồm:",
      avartar: "assets/avartar/08.jpg"),
  ChuyenGia(
      id: 9,
      money: 230000,
      chuyenMon: [
        1,
        2,
      ],
      kNLV: "Công ty CPLD ASB_2014-2019, Công ty TNHH ABECO_2020-202x",
      like: 835,
      name: "Nguyễn Tố Nga",
      nLBT: "Đầu tiên chúng ta nên tìm hiểu đôi chút về khái niệm điểm mạnh. Điểm mạnh (Strengths) là những thế mạnh của bạn về tố chất, kỹ năng, kinh nghiệm hoặc trình độ chuyên môn nổi trội trong đời sống và công việc của bản thân. Mỗi người trong chúng ta đều có các điểm mạnh khác nhau. Nhưng về cơ bản điểm mạnh thường bao gồm:",
      avartar: "assets/avartar/09.jpg"),
  ChuyenGia(
      id: 10,
      money: 1500000,
      chuyenMon: [5],
      kNLV: "Công ty CPLD ASB_2014-2019, Công ty TNHH ABECO_2020-202x",
      like: 165,
      name: "Hoàng Diệp Linh",
      nLBT: "Đầu tiên chúng ta nên tìm hiểu đôi chút về khái niệm điểm mạnh. Điểm mạnh (Strengths) là những thế mạnh của bạn về tố chất, kỹ năng, kinh nghiệm hoặc trình độ chuyên môn nổi trội trong đời sống và công việc của bản thân. Mỗi người trong chúng ta đều có các điểm mạnh khác nhau. Nhưng về cơ bản điểm mạnh thường bao gồm:",
      avartar: "assets/avartar/10.jpg"),
  ChuyenGia(
      id: 11,
      money: 485000,
      chuyenMon: [1, 3],
      kNLV: "Công ty CPLD ASB_2014-2019, Công ty TNHH ABECO_2020-202x",
      like: 765,
      name: "Hoàng Thảo",
      nLBT: "Đầu tiên chúng ta nên tìm hiểu đôi chút về khái niệm điểm mạnh. Điểm mạnh (Strengths) là những thế mạnh của bạn về tố chất, kỹ năng, kinh nghiệm hoặc trình độ chuyên môn nổi trội trong đời sống và công việc của bản thân. Mỗi người trong chúng ta đều có các điểm mạnh khác nhau. Nhưng về cơ bản điểm mạnh thường bao gồm:",
      avartar: "assets/avartar/11.jpg"),
  ChuyenGia(
      id: 12,
      money: 190000,
      chuyenMon: [3, 2, 6],
      kNLV: "Công ty CPLD ASB_2014-2019, Công ty TNHH ABECO_2020-202x",
      like: 402,
      name: "Văn Linh",
      nLBT: "Đầu tiên chúng ta nên tìm hiểu đôi chút về khái niệm điểm mạnh. Điểm mạnh (Strengths) là những thế mạnh của bạn về tố chất, kỹ năng, kinh nghiệm hoặc trình độ chuyên môn nổi trội trong đời sống và công việc của bản thân. Mỗi người trong chúng ta đều có các điểm mạnh khác nhau. Nhưng về cơ bản điểm mạnh thường bao gồm:",
      avartar: "assets/avartar/12.jpg"),
  ChuyenGia(
      id: 13,
      money: 250000,
      chuyenMon: [5, 3, 6],
      kNLV: "Công ty CPLD ASB_2014-2019, Công ty TNHH ABECO_2020-202x",
      like: 45,
      name: "Lê Hồng Hạnh",
      nLBT: "Đầu tiên chúng ta nên tìm hiểu đôi chút về khái niệm điểm mạnh. Điểm mạnh (Strengths) là những thế mạnh của bạn về tố chất, kỹ năng, kinh nghiệm hoặc trình độ chuyên môn nổi trội trong đời sống và công việc của bản thân. Mỗi người trong chúng ta đều có các điểm mạnh khác nhau. Nhưng về cơ bản điểm mạnh thường bao gồm:",
      avartar: "assets/avartar/13.jpg"),
  ChuyenGia(
      id: 14,
      money: 190000,
      chuyenMon: [5, 6],
      kNLV: "Công ty CPLD ASB_2014-2019, Công ty TNHH ABECO_2020-202x",
      like: 435,
      name: "Nguyễn Bá Thành",
      nLBT: "Đầu tiên chúng ta nên tìm hiểu đôi chút về khái niệm điểm mạnh. Điểm mạnh (Strengths) là những thế mạnh của bạn về tố chất, kỹ năng, kinh nghiệm hoặc trình độ chuyên môn nổi trội trong đời sống và công việc của bản thân. Mỗi người trong chúng ta đều có các điểm mạnh khác nhau. Nhưng về cơ bản điểm mạnh thường bao gồm:",
      avartar: "assets/avartar/14.jpg"),
];

